// flow-typed signature: 48c20afdbe55a224e2e5c6cd5a58d2ea
// flow-typed version: <<STUB>>/app-module-path_v^2.1.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'app-module-path'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'app-module-path' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'app-module-path/cwd' {
  declare module.exports: any;
}

declare module 'app-module-path/lib/index' {
  declare module.exports: any;
}

declare module 'app-module-path/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'app-module-path/cwd.js' {
  declare module.exports: $Exports<'app-module-path/cwd'>;
}
declare module 'app-module-path/lib/index.js' {
  declare module.exports: $Exports<'app-module-path/lib/index'>;
}
declare module 'app-module-path/register.js' {
  declare module.exports: $Exports<'app-module-path/register'>;
}
