// flow-typed signature: 9b8c0af3440d83ff38cdfdb828f077c3
// flow-typed version: <<STUB>>/babel-plugin-fetch-relay-schema_vfile:../fetch-relay-schema//flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-fetch-relay-schema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-fetch-relay-schema' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-fetch-relay-schema/src/fetchSchema' {
  declare module.exports: any;
}

declare module 'babel-plugin-fetch-relay-schema/src/generateSchema' {
  declare module.exports: any;
}

declare module 'babel-plugin-fetch-relay-schema/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-fetch-relay-schema/src/fetchSchema.js' {
  declare module.exports: $Exports<'babel-plugin-fetch-relay-schema/src/fetchSchema'>;
}
declare module 'babel-plugin-fetch-relay-schema/src/generateSchema.js' {
  declare module.exports: $Exports<'babel-plugin-fetch-relay-schema/src/generateSchema'>;
}
declare module 'babel-plugin-fetch-relay-schema/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-fetch-relay-schema/src/index'>;
}
