// flow-typed signature: 10a7f4effdf97f7dcf1ccc90d00c70c0
// flow-typed version: <<STUB>>/chrbala-linter_v^1.0.5/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chrbala-linter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'chrbala-linter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chrbala-linter/dist/index' {
  declare module.exports: any;
}

declare module 'chrbala-linter/rollup.config' {
  declare module.exports: any;
}

declare module 'chrbala-linter/src/index' {
  declare module.exports: any;
}

declare module 'chrbala-linter/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chrbala-linter/dist/index.js' {
  declare module.exports: $Exports<'chrbala-linter/dist/index'>;
}
declare module 'chrbala-linter/rollup.config.js' {
  declare module.exports: $Exports<'chrbala-linter/rollup.config'>;
}
declare module 'chrbala-linter/src/index.js' {
  declare module.exports: $Exports<'chrbala-linter/src/index'>;
}
declare module 'chrbala-linter/src/index.test.js' {
  declare module.exports: $Exports<'chrbala-linter/src/index.test'>;
}
