// flow-typed signature: 371f2ea9a74f5409e0577f4048381f29
// flow-typed version: <<STUB>>/relay-local-schema_v^0.5.5/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'relay-local-schema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'relay-local-schema' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'relay-local-schema/lib/__forks__/createRequestError' {
  declare module.exports: any;
}

declare module 'relay-local-schema/lib/__forks__/formatRequestErrors' {
  declare module.exports: any;
}

declare module 'relay-local-schema/lib/index' {
  declare module.exports: any;
}

declare module 'relay-local-schema/lib/NetworkLayer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'relay-local-schema/lib/__forks__/createRequestError.js' {
  declare module.exports: $Exports<'relay-local-schema/lib/__forks__/createRequestError'>;
}
declare module 'relay-local-schema/lib/__forks__/formatRequestErrors.js' {
  declare module.exports: $Exports<'relay-local-schema/lib/__forks__/formatRequestErrors'>;
}
declare module 'relay-local-schema/lib/index.js' {
  declare module.exports: $Exports<'relay-local-schema/lib/index'>;
}
declare module 'relay-local-schema/lib/NetworkLayer.js' {
  declare module.exports: $Exports<'relay-local-schema/lib/NetworkLayer'>;
}
