// flow-typed signature: 83c0ae706eaa209d377c2d082ea1a3d8
// flow-typed version: <<STUB>>/renamer_v^0.6.1/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'renamer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'renamer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'renamer/bin/cli' {
  declare module.exports: any;
}

declare module 'renamer/lib/cliOptions' {
  declare module.exports: any;
}

declare module 'renamer/lib/renamer' {
  declare module.exports: any;
}

declare module 'renamer/lib/Result' {
  declare module.exports: any;
}

declare module 'renamer/lib/Results' {
  declare module.exports: any;
}

// Filename aliases
declare module 'renamer/bin/cli.js' {
  declare module.exports: $Exports<'renamer/bin/cli'>;
}
declare module 'renamer/lib/cliOptions.js' {
  declare module.exports: $Exports<'renamer/lib/cliOptions'>;
}
declare module 'renamer/lib/renamer.js' {
  declare module.exports: $Exports<'renamer/lib/renamer'>;
}
declare module 'renamer/lib/Result.js' {
  declare module.exports: $Exports<'renamer/lib/Result'>;
}
declare module 'renamer/lib/Results.js' {
  declare module.exports: $Exports<'renamer/lib/Results'>;
}
